spring:

  ### jooq
  jooq:
    sql-dialect: POSTGRES

  ### data source
  datasource:
    #url: jdbc:postgresql://localhost:25432/jooqdemodb
    url: jdbc:log4jdbc:postgresql://localhost:25432/jooqdemodb
    #drivefClassName: org.postgresql.Driver
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: jooqdemouser
    password: jooqdemouser
    type: com.zaxxer.hikari.HikariDataSource

    # for HikarCP
    hikari:
      auto-commit: false
